### ISSUE TITLE
issue with pytorch 0.3

### ISSUE THREAD

**Issue by jwnsu** [galsang/CNN-sentence-classification-pytorch#2]
ran into core dump (after word2vec loading): 
 `(core dumped) python3 ./run.py --model non-static --dataset MR --gpu 1`

Env: pytorch 0.3 (CUDA9.0)/Python 3.5.2/ubuntu 16.04.03 (numpy 1.14.1)

Replaced a few python 3.6 f-string to be 3.5 compatible.

Does it require pytorch 0.2.x?

**Comment by galsang** [comment]
First of all, I highly recommend you to use python **3.6** when running the code.
Note that f-strings only available at python 3.6 (or above) also exist in _model.py._
If you wanna run in 3.5, that part should be modified appropriately.

**Comment by jwnsu** [comment]
Thx. f-strings are easy and has been changed. Tried latest pytorch 3.1, still got core dump in training code, it seems something structural. What pytorch version did this code repository test on?

ps: upgrade to python 3.6 will cause compatibility issues for other projects.

**Comment by jwnsu** [comment]
my error, in model.py when replacing f-string, forgot to add a parameter value for {i} inside f-string. It works fine after fix it. 

Thx for your project!
